auto commit sans commentaire

diff --git a/certsFiles/generate_certificate_with_certbot b/certsFiles/generate_certificate_with_certbot
--- a/certsFiles/generate_certificate_with_certbot
+++ b/certsFiles/generate_certificate_with_certbot
@@ -1,4 +1,19 @@
 #!/bin/bash
+if ! dpkg -s nodejs | grep Status | grep -q installed > /dev/null 2>&1; then
+      echo "error nodejs isn't installed"
+      echo "terminating the process..."
+      exit 1
+fi
+if ! dpkg -s certbot | grep Status | grep -q installed > /dev/null 2>&1; then
+      echo "error certbot isn't installed"
+      echo "terminating the process..."
+      exit 1
+fi
+if sudo lsof -i -P -n | grep ":80" > /dev/null 2>&1; then
+      echo "error port 80 is already used"
+      echo "terminating the process..."
+      exit 1
+fi
 cd ../
 line=$(grep "WEBSITE_URL" .env)
 value=`echo "$line" | cut -d "=" -f 2`
